from woob.capabilities.housing import HOUSE_TYPES, POSTS_TYPES


TYPES = {POSTS_TYPES.RENT: "1", POSTS_TYPES.SALE: "4"}

RET = {
    HOUSE_TYPES.HOUSE: "2",
    HOUSE_TYPES.APART: "1",
    HOUSE_TYPES.LAND: "3",
    HOUSE_TYPES.PARKING: "4",
    HOUSE_TYPES.OTHER: "5",
}
