from woob.capabilities.housing import HOUSE_TYPES, POSTS_TYPES


QUERY_TYPES = {POSTS_TYPES.RENT: 2, POSTS_TYPES.SALE: 1, POSTS_TYPES.VIAGER: 3, POSTS_TYPES.FURNISHED_RENT: 2}

QUERY_HOUSE_TYPES = {
    HOUSE_TYPES.APART: [1],
    HOUSE_TYPES.HOUSE: [2],
    HOUSE_TYPES.PARKING: [4],
    HOUSE_TYPES.LAND: [3],
    HOUSE_TYPES.OTHER: [10, 11],
    HOUSE_TYPES.UNKNOWN: range(1, 12),
}

HOUSE_TYPES_LABELS = {
    "Appartement": HOUSE_TYPES.APART,
    "Maison": HOUSE_TYPES.HOUSE,
    "Parking": HOUSE_TYPES.PARKING,
    "Terrains": HOUSE_TYPES.LAND,
    "Forêts": HOUSE_TYPES.OTHER,
    "Propriétés agricole/viticole ": HOUSE_TYPES.OTHER,
}
